version: "3.9"
services:
  ansible:
    dns:
     - 8.8.8.8
     - 8.8.4.4
    secrets:
      - secret_vars
    image: cytopia/ansible
    tty: true
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    volumes:
      - ~/.ssh/:/root/.ssh/:ro
      - ./ansible:/data
      - ./:/netology
    command: ansible-playbook -i /data/inventories/hosts playbook.yml --tags "read_secrets_variable, install_in_one"
secrets:
    secret_vars:
      file: /Users/oleginishev/secret_vars.yml
