global:
  scrape_interval:     15s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: django-candydendy
    scrape_interval: 10s
    static_configs:
      - targets: ['candydendy:8000']
  - job_name: postgres-exporter
    static_configs:
      - targets: ["dbexporter:9187"]
  - job_name: nginx-exporter
    static_configs:
      - targets: ['nginx-exporter:9113']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9323','cadvisor:8080','node-exporter:9100', 'nginx-exporter:9113']
