---
- name: install_in_one
  gather_facts: false
  hosts: all
  vars_files:
    - /run/secrets/secret_vars
  tasks:
    - name: install_in_one
      include_role:
        name: install_in_one
  tags:
    - install_in_one
